export const frameworks = [
    { name: 'React', image: 'react.png' },
    { name: 'Angular', image: 'angular.png' },
    { name: 'Vue.js', image: 'vue.png' },
    { name: 'Node.js', image: 'nodejs.png' },
    { name: 'Express.js', image: 'express.png' },
    { name: 'Django', image: 'django.png' },
    { name: 'Flask', image: 'flask.png' },
    { name: 'Ruby on Rails', image: 'rails.png' },
    { name: 'Spring', image: 'spring.png' },
    { name: 'ASP.NET', image: 'aspnet.png' },
    { name: 'Laravel', image: 'laravel.png' },
    { name: 'Symfony', image: 'symfony.png' },
    { name: 'Meteor', image: 'meteor.png' },
    { name: 'Ember.js', image: 'ember.png' },
    { name: 'Backbone.js', image: 'backbone.png' },
    { name: 'jQuery', image: 'jquery.png' },
    { name: 'Bootstrap', image: 'bootstrap.png' },
    { name: 'Tailwind CSS', image: 'tailwind.png' },
    { name: 'Sass', image: 'sass.png' },
    { name: 'Less', image: 'less.png' },
    { name: 'D3.js', image: 'd3.png' },
    { name: 'Three.js', image: 'three.png' },
    { name: 'Unity', image: 'unity.png' },
    { name: 'Unreal Engine', image: 'unreal.png' },
    { name: 'OpenGL', image: 'opengl.png' },
    { name: 'DirectX', image: 'directx.png' },
    { name: 'C++', image: 'cpp.png' },
    { name: 'Java', image: 'java.png' },
    { name: 'Python', image: 'python.png' },
    { name: 'C#', image: 'csharp.png' },
    { name: 'Ruby', image: 'ruby.png' },
    { name: 'PHP', image: 'php.png' },
    { name: 'JavaScript', image: 'javascript.png' },
    { name: 'TypeScript', image: 'typescript.png' },
    { name: 'HTML', image: 'html.png' },
    { name: 'CSS', image: 'css.png' },
    { name: 'SQL', image: 'sql.png' },
    { name: 'NoSQL', image: 'nosql.png' },
    { name: 'MongoDB', image: 'mongodb.png' },
    { name: 'Firebase', image: 'firebase.png' },
    { name: 'PostgreSQL', image: 'postgresql.png' },
    { name: 'MySQL', image: 'mysql.png' },
    { name: 'SQLite', image: 'sqlite.png' },
    { name: 'Oracle', image: 'oracle.png' },

];
