export const frameworks = [
    { name: 'React', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710411479479.png?alt=media&token=3fd5681c-e291-49a5-b2ac-c474858dd28b' },
    { name: 'Angular', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710411745851.png?alt=media&token=081967b9-0a01-43f7-bbfb-f6ef9baaa7fb' },
    { name: 'Vue.js', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710414779923.png?alt=media&token=15646de4-d1f4-48b7-9ea1-d2bae88b0568' },
    { name: 'Node.js', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710414912677.png?alt=media&token=cf583c3f-eb76-48db-b936-10db6280bb37' },
    { name: 'Express.js', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710415144195.png?alt=media&token=4ee8e628-b98c-440d-b519-3071fcce109f' },
    { name: 'Django', image: 'django.png' },
    { name: 'Flask', image: 'flask.png' },
    { name: 'Ruby on Rails', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710415745513.png?alt=media&token=4b27cb76-945c-48ed-b017-2ad3710e8019' },
    { name: 'Spring', image: 'spring.png' },
    { name: 'ASP.NET', image: 'aspnet.png' },
    { name: 'Laravel', image: 'laravel.png' },
    { name: 'Symfony', image: 'symfony.png' },
    { name: 'Meteor', image: 'meteor.png' },
    { name: 'Ember.js', image: 'ember.png' },
    { name: 'Backbone.js', image: 'backbone.png' },
    { name: 'jQuery', image: 'jquery.png' },
    { name: 'Bootstrap', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-95a3d.appspot.com/o/domains%2F1710415946740.png?alt=media&token=268db3d2-f8e3-42ad-af23-39b2b3babdb5' },
    { name: 'Tailwind CSS', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-9ee16.appspot.com/o/frameWorks%2Ftailwind.png?alt=media&token=de009f26-fe65-462e-bf74-90e3bc97af8f' },
    { name: 'Sass', image: 'sass.png' },
    { name: 'Less', image: 'less.png' },
    { name: 'D3.js', image: 'd3.png' },
    { name: 'Three.js', image: 'three.png' },
    { name: 'Unity', image: 'unity.png' },
    { name: 'Unreal Engine', image: 'unreal.png' },
    { name: 'OpenGL', image: 'opengl.png' },
    { name: 'DirectX', image: 'directx.png' },
    { name: 'C++', image: 'cpp.png' },
    { name: 'Java', image: 'java.png' },
    { name: 'Python', image: 'python.png' },
    { name: 'C#', image: 'csharp.png' },
    { name: 'Ruby', image: 'ruby.png' },
    { name: 'PHP', image: 'php.png' },
    { name: 'JavaScript', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-9ee16.appspot.com/o/frameWorks%2Fjs%20.png?alt=media&token=f3548f0c-b933-486e-9e4f-07dcbd948681' },
    { name: 'TypeScript', image: 'typescript.png' },
    { name: 'HTML', image: 'html.png' },
    { name: 'CSS', image: 'css.png' },
    { name: 'SQL', image: 'sql.png' },
    { name: 'NoSQL', image: 'nosql.png' },
    { name: 'MongoDB', image: 'https://firebasestorage.googleapis.com/v0/b/codelab-9ee16.appspot.com/o/frameWorks%2Fmongodb-removebg-preview.png?alt=media&token=1eb4c93f-0fcc-4877-90c2-c6892fd8cade' },
    { name: 'Firebase', image: 'firebase.png' },
    { name: 'PostgreSQL', image: 'postgresql.png' },
    { name: 'MySQL', image: 'mysql.png' },
    { name: 'SQLite', image: 'sqlite.png' },
    { name: 'Oracle', image: 'oracle.png' },

];
